import React, {useState} from 'react';
import {Routes, Route, Link, NavLink, useNavigate, useParams} from 'react-router-dom';
import {Search, Scale, BadgeCheck, MapPin, Star, CalendarDays, Users, ArrowRight, Check, Menu, X, LayoutDashboard, Building2, ClipboardList, BarChart3, Percent, Flag, Trash2, Upload, Wrench, CreditCard} from 'lucide-react';
import {properties} from './data';

const Footer=()=> <footer>Made by Devansh Sheth, Usman Kazi & Ryshaan Shah</footer>;

function Navbar({publicNav=false}){
 const [open,setOpen]=useState(false);
 return <header className="navbar"><Link className="brand" to="/"><span>HIRE</span><small>Hotels, Inns & Restaurants Ecosystem</small></Link>
  <button className="menu" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button>
  <nav className={open?'open':''}>{publicNav ? <><NavLink to="/">Home</NavLink><NavLink to="/search">Search</NavLink><NavLink to="/compare">Compare</NavLink><NavLink to="/login">Login</NavLink></> : <><NavLink to="/">Home</NavLink><NavLink to="/search">Search</NavLink><NavLink to="/compare">Compare</NavLink><NavLink to="/dashboard">Dashboard</NavLink></>}</nav>
 </header>
}
const Layout=({children,publicNav=false})=><><Navbar publicNav={publicNav}/>{children}<Footer/></>;
const Button=({children,to,onClick,secondary=false,type='button'})=> to?<Link className={'btn '+(secondary?'btn-secondary':'')} to={to}>{children}</Link>:<button type={type} onClick={onClick} className={'btn '+(secondary?'btn-secondary':'')}>{children}</button>;

function Home(){return <Layout publicNav><main>
 <section className="hero"><div className="hero-copy"><p className="eyebrow">Hotels · Inns · Restaurants</p><h1>HIRE</h1><h2>Hotels, Inns & Restaurants Ecosystem</h2><p>Book smarter. Hire from us.</p><div className="actions"><Button to="/login">Login</Button><Button to="/search" secondary>Browse as Guest</Button></div></div></section>
 <section className="section"><h2 className="center">Why people use HIRE</h2><div className="three-grid"><Info icon={<Search/>} title="Find the right place">Filter by location, price, rating, and type to find exactly what you're looking for — no noise, no clutter.</Info><Info icon={<Scale/>} title="Compare before you book">Put any two properties side by side and compare what matters: price, amenities, and real critic scores.</Info><Info icon={<BadgeCheck/>} title="Honest critic reviews">Every review on HIRE comes from a verified critic who's actually visited. No fake stars, no paid rankings.</Info></div></section>
 <section className="section shaded"><div className="section-head"><h2>Featured properties</h2><Link to="/search">Browse all <ArrowRight size={16}/></Link></div><div className="three-grid cards">{properties.slice(0,3).map(p=><PropertyCard key={p.id} p={p}/>)}</div></section>
 </main></Layout>}
function Info({icon,title,children}){return <div className="info-card"><div className="icon">{icon}</div><h3>{title}</h3><p>{children}</p></div>}
function PropertyCard({p,compact=false}){return <article className={'property-card '+(compact?'compact':'')}><img src={p.image} alt={p.name}/><div className="property-body"><div className="type">{p.type}</div><h3>{p.name}</h3><p className="location"><MapPin size={15}/>{p.location}</p><div className="meta"><span className="rating"><Star size={15} fill="currentColor"/>{p.rating}</span><strong>₹{p.price.toLocaleString()} <small>/ night</small></strong></div><Button to={'/property/'+p.id}>{compact?'View':'View property'}</Button></div></article>}

function Login(){const nav=useNavigate(); const [mode,setMode]=useState('login'); return <Layout publicNav><main className="auth-page"><div className="auth-card"><p className="eyebrow">Welcome to HIRE</p><h1>{mode==='login'?'Log in':'Create account'}</h1><p className="muted">{mode==='login'?'Use your account to continue booking.':'A simple account for managing your bookings.'}</p><form onSubmit={e=>{e.preventDefault();nav('/search')}}><label>Email<input type="email" placeholder="you@example.com" required/></label><label>Password<input type="password" placeholder="••••••••" required/></label>{mode==='signup'&&<label>Name<input placeholder="Your name" required/></label>}<button className="btn full" type="submit">{mode==='login'?'Continue':'Sign up'}</button></form><button className="text-btn" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'New here? Create an account':'Already have an account? Log in'}</button><div className="divider"><span>or</span></div><Button to="/admin" secondary>Continue as Admin / Manager / Critic</Button></div></main></Layout>}

function SearchPage(){const [q,setQ]=useState(''); const [type,setType]=useState('All'); const [min,setMin]=useState(0); const [max,setMax]=useState(10000); const filtered=properties.filter(p=>(!q||p.name.toLowerCase().includes(q.toLowerCase())||p.location.toLowerCase().includes(q.toLowerCase()))&&(type==='All'||p.type===type)&&p.rating>=min&&p.price<=max); return <Layout><main className="page"><div className="page-title"><div><p className="eyebrow">Browse</p><h1>Find a place that fits</h1><p className="muted">Search hotels, inns and restaurants with simple filters.</p></div></div><div className="search-layout"><aside className="filters"><h3>Filters</h3><label>Location<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Mumbai, Goa..."/></label><label>Price up to <b>₹{max.toLocaleString()}</b><input type="range" min="1000" max="10000" step="500" value={max} onChange={e=>setMax(+e.target.value)}/></label><label>Minimum rating<select value={min} onChange={e=>setMin(+e.target.value)}><option value="0">Any rating</option><option value="4">4.0+</option><option value="4.5">4.5+</option><option value="4.8">4.8+</option></select></label><label>Type<select value={type} onChange={e=>setType(e.target.value)}><option>All</option><option>Hotel</option><option>Inn</option><option>Restaurant</option></select></label><Button to="/compare" secondary>Go to Compare</Button></aside><section><div className="results-bar"><b>{filtered.length} places found</b><span>Sorted by rating</span></div><div className="results-grid">{filtered.map(p=><PropertyCard key={p.id} p={p}/>)}</div></section></div></main></Layout>}

function Property(){const {id}=useParams();const p=properties.find(x=>x.id===+id)||properties[0]; const [tab,setTab]=useState('Overview'); return <Layout><main className="page"><div className="detail-hero"><img src={p.image} alt={p.name}/><div className="detail-title"><span className="pill">{p.type}</span><h1>{p.name}</h1><p><MapPin size={16}/>{p.location}</p><div className="rating large"><Star size={17} fill="currentColor"/>{p.rating} <span>({p.reviews} reviews)</span></div></div></div><div className="detail-actions"><strong>₹{p.price.toLocaleString()} <small>/ night</small></strong><div><Button to={'/booking/'+p.id}>Book Now</Button><Button to="/compare" secondary>Add to Compare</Button></div></div><div className="tabs">{['Overview','Amenities','Reviews','Availability'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><section className="detail-content">{tab==='Overview'&&<><h2>About this place</h2><p>A comfortable, well-reviewed place with straightforward pricing and the essentials you need for a good stay.</p><div className="amenities">{p.amenities.map(a=><span key={a}><Check size={15}/>{a}</span>)}</div></>}{tab==='Amenities'&&<><h2>Amenities</h2><div className="amenities">{p.amenities.map(a=><span key={a}><Check size={15}/>{a}</span>)}</div></>}{tab==='Reviews'&&<><h2>Verified reviews</h2><div className="review"><BadgeCheck/><div><b>Verified Critic</b><div className="stars">★★★★★</div><p>Clean, comfortable and matched the listing. Good value for the price.</p></div></div><div className="review"><BadgeCheck/><div><b>Verified Critic</b><div className="stars">★★★★☆</div><p>Friendly service and a pleasant stay.</p></div></div></>}{tab==='Availability'&&<><h2>Availability</h2><div className="availability-box"><CalendarDays/><div><b>Choose your dates on the booking page</b><p className="muted">Live availability is represented here as a simple demo flow.</p></div><Button to={'/booking/'+p.id}>Choose dates</Button></div></>}</section></main></Layout>}

function Compare(){const [ids,setIds]=useState([1,2]);const selected=ids.map(id=>properties.find(p=>p.id===+id)).filter(Boolean);return <Layout><main className="page"><div className="page-title"><p className="eyebrow">Compare</p><h1>Compare before you book</h1><p className="muted">Pick two properties and see the important details side by side.</p></div><div className="compare-controls">{[0,1].map(i=><select key={i} value={ids[i]} onChange={e=>{const next=[...ids];next[i]=+e.target.value;setIds(next)}}>{properties.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select>)}</div><div className="compare-table"><div className="compare-row header"><div>Details</div>{selected.map(p=><div key={p.id}><img src={p.image}/><h3>{p.name}</h3><p>{p.location}</p></div>)}</div><CompareRow label="Price" vals={selected.map(p=>'₹'+p.price.toLocaleString()+'/ night')}/><CompareRow label="Rating" vals={selected.map(p=>p.rating+' / 5')}/><CompareRow label="Type" vals={selected.map(p=>p.type)}/><CompareRow label="Amenities" vals={selected.map(p=>p.amenities.join(', '))}/><CompareRow label="Reviews" vals={selected.map(p=>p.reviews+' verified reviews')}/></div><div className="center"><Button to={'/property/'+selected[0].id}>Continue with {selected[0].name}</Button></div></main></Layout>}
function CompareRow({label,vals}){return <div className="compare-row"><b>{label}</b>{vals.map((v,i)=><div key={i}>{v}</div>)}</div>}

function Booking(){const {id}=useParams();const p=properties.find(x=>x.id===+id)||properties[0];const [done,setDone]=useState(false);const [guests,setGuests]=useState(2);return <Layout><main className="page narrow">{done?<div className="confirmation"><div className="success"><Check/></div><p className="eyebrow">Booking confirmed</p><h1>You're all set!</h1><p>Your stay at <b>{p.name}</b> has been booked for {guests} guests.</p><Button to="/feedback/1">Leave feedback after your stay</Button><Button to="/search" secondary>Back to Search</Button></div>:<><div className="page-title"><p className="eyebrow">Booking</p><h1>Book {p.name}</h1></div><div className="booking-grid"><form className="form-card" onSubmit={e=>{e.preventDefault();setDone(true)}}><div className="form-grid"><label>Check-in<input type="date" required/></label><label>Check-out<input type="date" required/></label></div><label>Guests<select value={guests} onChange={e=>setGuests(+e.target.value)}>{[1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label><h3>Payment</h3><label>Card number<input placeholder="1234 5678 9012 3456" required/></label><div className="form-grid"><label>Expiry<input placeholder="MM/YY" required/></label><label>CVV<input placeholder="123" required/></label></div><button className="btn full" type="submit"><CreditCard size={17}/>Pay & Confirm</button></form><aside className="price-card"><img src={p.image} alt=""/><h3>{p.name}</h3><p className="muted">₹{p.price.toLocaleString()} × 1 night</p><div className="price-line"><span>Room</span><b>₹{p.price.toLocaleString()}</b></div><div className="price-line"><span>Service fee</span><b>₹{Math.round(p.price*.08).toLocaleString()}</b></div><hr/><div className="price-line total"><span>Total</span><b>₹{Math.round(p.price*1.08).toLocaleString()}</b></div></aside></div></>}</main></Layout>}

function Feedback(){const [sent,setSent]=useState(false);return <Layout><main className="page narrow">{sent?<div className="confirmation"><div className="success"><Check/></div><h1>Thanks for your feedback!</h1><p>Your review helps future guests choose with confidence.</p><Button to="/search">Browse more places</Button></div>:<div className="form-card"><p className="eyebrow">Post-stay feedback</p><h1>How was your stay?</h1><p className="muted">This is separate from critic reviews and is only available after a completed booking.</p><label>Rating<div className="rating-picker">{[1,2,3,4,5].map(n=><button type="button" key={n}>★</button>)}</div></label><label>Your comment<textarea rows="5" placeholder="Tell us what went well..."></textarea></label><button className="btn" onClick={()=>setSent(true)}>Submit feedback</button></div>}</main></Layout>}

function Dashboard(){return <Layout><main className="page"><div className="dashboard-grid"><aside className="side"><div className="side-title"><LayoutDashboard/>Dashboard</div><NavLink to="/dashboard"><Building2/>My Property</NavLink><NavLink to="/dashboard"><ClipboardList/>Bookings</NavLink><NavLink to="/dashboard"><Percent/>Discounts</NavLink><NavLink to="/dashboard"><BarChart3/>Reports</NavLink></aside><section><p className="eyebrow">Manager dashboard</p><h1>Good morning, Manager</h1><div className="stat-grid"><Stat label="Bookings this month" value="42"/><Stat label="Occupancy" value="78%"/><Stat label="Rating" value="4.8"/></div><div className="form-card"><h2>My Property</h2><div className="form-grid"><label>Property name<input defaultValue="Grand Palace Hotel"/></label><label>Location<input defaultValue="Mumbai, India"/></label></div><label>Description<textarea defaultValue="A comfortable city hotel with easy access to central Mumbai."/></label><h3>Photos</h3><div className="upload-grid"><div><Upload/><span>Drop image here</span></div><div><Upload/><span>Drop image here</span></div><div><Upload/><span>Drop image here</span></div></div><h3>Amenities under repair</h3><div className="toggle-list"><Toggle label="Swimming pool"/><Toggle label="Gym" on/><Toggle label="Restaurant"/></div><Button>Save changes</Button></div><div className="form-card"><h2>Current bookings</h2><table><thead><tr><th>Guest</th><th>Dates</th><th>Guests</th><th>Status</th></tr></thead><tbody><tr><td>Aarav</td><td>12–14 Sep</td><td>2</td><td><span className="status good">Confirmed</span></td></tr><tr><td>Meera</td><td>18–20 Sep</td><td>3</td><td><span className="status good">Confirmed</span></td></tr><tr><td>Rohan</td><td>21–22 Sep</td><td>1</td><td><span className="status">Pending</span></td></tr></tbody></table></div></section></div></main></Layout>}
function Stat({label,value}){return <div className="stat"><span>{label}</span><strong>{value}</strong></div>}
function Toggle({label,on=false}){const [v,setV]=useState(on);return <button className="toggle-row" onClick={()=>setV(!v)}><span>{label}</span><span className={'switch '+(v?'on':'')}><i/></span></button>}

function Critic(){return <Layout><main className="page"><div className="page-title"><p className="eyebrow">Critic dashboard</p><h1>Places waiting for a review</h1><p className="muted">Only verified critics can publish critic reviews.</p></div><div className="results-grid">{properties.slice(0,4).map(p=><article className="review-card" key={p.id}><img src={p.image} alt=""/><div><span className="pill">Visited</span><h3>{p.name}</h3><p>{p.location}</p><Button to={'/critic/review/'+p.id}>Write Review</Button></div></article>)}</div></main></Layout>}
function CriticReview(){const {id}=useParams();const p=properties.find(x=>x.id===+id)||properties[0];const [sent,setSent]=useState(false);return <Layout><main className="page narrow">{sent?<div className="confirmation"><div className="success"><Check/></div><h1>Review published</h1><p>Your review of {p.name} now shows with a Verified Critic badge.</p><Button to="/critic">Back to Critic Dashboard</Button></div>:<div className="form-card"><p className="eyebrow">Verified Critic</p><h1>Review {p.name}</h1>{['Cleanliness','Service','Food','Ambience','Value'].map(x=><label key={x}>{x}<select><option>5 — Excellent</option><option>4 — Good</option><option>3 — Okay</option><option>2 — Poor</option><option>1 — Bad</option></select></label>)}<label>Suggestions<textarea rows="6" placeholder="What should future guests know?"></textarea></label><button className="btn" onClick={()=>setSent(true)}>Publish Review</button></div>}</main></Layout>}

function ManagerRegister(){const nav=useNavigate();return <Layout><main className="page narrow"><div className="form-card"><p className="eyebrow">For property managers</p><h1>Register your property</h1><p className="muted">Add your place and activate it with a simple mock payment.</p><label>Property name<input placeholder="Your hotel or inn"/></label><div className="form-grid"><label>Type<select><option>Hotel</option><option>Inn</option><option>Restaurant</option></select></label><label>City<input placeholder="Mumbai"/></label></div><label>Address<input placeholder="Full address"/></label><label>About your property<textarea rows="4" placeholder="A short description"></textarea></label><h3>Activation payment</h3><div className="price-line"><span>Listing activation</span><b>₹999</b></div><button className="btn full" onClick={()=>nav('/dashboard')}>Pay ₹999 & Activate</button></div></main></Layout>}

function Admin(){const [rows,setRows]=useState(properties.slice(0,5).map((p,i)=>({...p,status:i===3?'Flagged':'Active'})));const act=(id,status)=>setRows(r=>r.map(x=>x.id===id?{...x,status}:x));return <Layout><main className="page"><div className="page-title"><p className="eyebrow">Admin</p><h1>Keep HIRE clean and useful</h1><p className="muted">Review properties and critic accounts at a glance.</p></div><div className="admin-tabs"><button className="active">Properties</button><button>Critics</button></div><div className="table-card"><table><thead><tr><th>Property</th><th>Type</th><th>Rating</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.name}</b><small>{r.location}</small></td><td>{r.type}</td><td>{r.rating}</td><td><span className={'status '+(r.status==='Active'?'good':'warn')}>{r.status}</span></td><td><div className="row-actions"><button onClick={()=>act(r.id,'Flagged')} title="Flag"><Flag size={16}/></button><button onClick={()=>act(r.id,'Removed')} title="Remove"><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div></main></Layout>}

function NotFound(){return <Layout><main className="auth-page"><div className="auth-card center"><h1>Page not found</h1><p className="muted">The page you're looking for doesn't exist.</p><Button to="/">Go home</Button></div></main></Layout>}

export default function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/login" element={<Login/>}/><Route path="/search" element={<SearchPage/>}/><Route path="/property/:id" element={<Property/>}/><Route path="/compare" element={<Compare/>}/><Route path="/booking/:id" element={<Booking/>}/><Route path="/feedback/:bookingId" element={<Feedback/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/critic" element={<Critic/>}/><Route path="/critic/review/:id" element={<CriticReview/>}/><Route path="/manager/register" element={<ManagerRegister/>}/><Route path="/admin" element={<Admin/>}/><Route path="*" element={<NotFound/>}/></Routes>}
